name: Terraform Init Deployment
on: push
jobs:
    init:
        runs-on: ubuntu-latest
        steps:
            - name: Get code
            uses: actions/checkout@v3
            - name: Run terraform init command
            run: terraform init
    validate:
        runs-on: ubuntu-latest
        steps:
            - name: Get code
            uses: actions/checkout@v3
            - name: Run terraform init command
            run: terraform validate
            - name: Run terraform fmt command
            run: terraform fmt command
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Get code
              uses: actions/checkout@v3
            - name: Run terraform plan command
              run: terraform plan -var-file ./env/dev.tfvars
